// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeEdutify.Persistence.Context;

#nullable disable

namespace TradeEdutify.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231126154001_UserDefaultPortfolioAndTransactionLog")]
    partial class UserDefaultPortfolioAndTransactionLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradeEdutify.Domain.Entities.Portfolio", b =>
                {
                    b.Property<long>("PortfolioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PortfolioID"));

                    b.Property<DateTimeOffset>("OperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ShareID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("PortfolioID");

                    b.HasIndex("ShareID");

                    b.HasIndex("UserID");

                    b.ToTable("Portfolio");

                    b.HasData(
                        new
                        {
                            PortfolioID = 100L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9812), new TimeSpan(0, 3, 0, 0, 0)),
                            ShareID = 100L,
                            UserID = 100L
                        },
                        new
                        {
                            PortfolioID = 101L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9814), new TimeSpan(0, 3, 0, 0, 0)),
                            ShareID = 102L,
                            UserID = 101L
                        },
                        new
                        {
                            PortfolioID = 102L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9816), new TimeSpan(0, 3, 0, 0, 0)),
                            ShareID = 103L,
                            UserID = 101L
                        },
                        new
                        {
                            PortfolioID = 103L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9818), new TimeSpan(0, 3, 0, 0, 0)),
                            ShareID = 104L,
                            UserID = 102L
                        },
                        new
                        {
                            PortfolioID = 104L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9820), new TimeSpan(0, 3, 0, 0, 0)),
                            ShareID = 103L,
                            UserID = 102L
                        });
                });

            modelBuilder.Entity("TradeEdutify.Domain.Entities.Share", b =>
                {
                    b.Property<long>("ShareID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ShareID"));

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShareID");

                    b.ToTable("Share");

                    b.HasData(
                        new
                        {
                            ShareID = 100L,
                            LastUpdateDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9746), new TimeSpan(0, 3, 0, 0, 0)),
                            Rate = 45.43,
                            Symbol = "AGT"
                        },
                        new
                        {
                            ShareID = 101L,
                            LastUpdateDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9786), new TimeSpan(0, 3, 0, 0, 0)),
                            Rate = 30.16,
                            Symbol = "THY"
                        },
                        new
                        {
                            ShareID = 102L,
                            LastUpdateDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9788), new TimeSpan(0, 3, 0, 0, 0)),
                            Rate = 70.319999999999993,
                            Symbol = "EGS"
                        },
                        new
                        {
                            ShareID = 103L,
                            LastUpdateDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9790), new TimeSpan(0, 3, 0, 0, 0)),
                            Rate = 120.76000000000001,
                            Symbol = "ODR"
                        },
                        new
                        {
                            ShareID = 104L,
                            LastUpdateDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9793), new TimeSpan(0, 3, 0, 0, 0)),
                            Rate = 12.1,
                            Symbol = "VHY"
                        });
                });

            modelBuilder.Entity("TradeEdutify.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionID"));

                    b.Property<DateTimeOffset>("OperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("ShareID")
                        .HasColumnType("bigint");

                    b.Property<double>("TotalOperationPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("TradeType")
                        .HasColumnType("integer");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("TransactionID");

                    b.HasIndex("ShareID");

                    b.HasIndex("UserID");

                    b.ToTable("Transaction");

                    b.HasData(
                        new
                        {
                            TransactionID = 100L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9835), new TimeSpan(0, 3, 0, 0, 0)),
                            Quantity = 3,
                            ShareID = 100L,
                            TotalOperationPrice = 136.28999999999999,
                            TradeType = 0,
                            UnitPrice = 45.439999999999998,
                            UserID = 100L
                        },
                        new
                        {
                            TransactionID = 101L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9838), new TimeSpan(0, 3, 0, 0, 0)),
                            Quantity = 20,
                            ShareID = 102L,
                            TotalOperationPrice = 603.20000000000005,
                            TradeType = 0,
                            UnitPrice = 30.16,
                            UserID = 101L
                        },
                        new
                        {
                            TransactionID = 103L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9841), new TimeSpan(0, 3, 0, 0, 0)),
                            Quantity = 10,
                            ShareID = 103L,
                            TotalOperationPrice = 1207.6000000000001,
                            TradeType = 0,
                            UnitPrice = 120.76000000000001,
                            UserID = 101L
                        },
                        new
                        {
                            TransactionID = 104L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9843), new TimeSpan(0, 3, 0, 0, 0)),
                            Quantity = 5,
                            ShareID = 103L,
                            TotalOperationPrice = 628.80000000000007,
                            TradeType = 1,
                            UnitPrice = 125.76000000000001,
                            UserID = 101L
                        },
                        new
                        {
                            TransactionID = 105L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9845), new TimeSpan(0, 3, 0, 0, 0)),
                            Quantity = 5,
                            ShareID = 104L,
                            TotalOperationPrice = 60.5,
                            TradeType = 0,
                            UnitPrice = 12.1,
                            UserID = 102L
                        },
                        new
                        {
                            TransactionID = 106L,
                            OperationDate = new DateTimeOffset(new DateTime(2023, 11, 26, 18, 40, 1, 265, DateTimeKind.Unspecified).AddTicks(9847), new TimeSpan(0, 3, 0, 0, 0)),
                            Quantity = 20,
                            ShareID = 103L,
                            TotalOperationPrice = 2415.2000000000003,
                            TradeType = 0,
                            UnitPrice = 120.76000000000001,
                            UserID = 102L
                        });
                });

            modelBuilder.Entity("TradeEdutify.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserID"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 100L,
                            Username = "Ethan Hayes"
                        },
                        new
                        {
                            UserID = 101L,
                            Username = "Olivia Foster"
                        },
                        new
                        {
                            UserID = 102L,
                            Username = "Amelia Rodriguez"
                        },
                        new
                        {
                            UserID = 103L,
                            Username = "Sophia Chang"
                        },
                        new
                        {
                            UserID = 104L,
                            Username = "Jackson Bennett"
                        });
                });

            modelBuilder.Entity("TradeEdutify.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("TradeEdutify.Domain.Entities.Share", "Share")
                        .WithMany("Portfolios")
                        .HasForeignKey("ShareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeEdutify.Domain.Entities.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Share");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradeEdutify.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("TradeEdutify.Domain.Entities.Share", null)
                        .WithMany("Transactions")
                        .HasForeignKey("ShareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeEdutify.Domain.Entities.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradeEdutify.Domain.Entities.Share", b =>
                {
                    b.Navigation("Portfolios");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TradeEdutify.Domain.Entities.User", b =>
                {
                    b.Navigation("Portfolios");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
